Issue56
sarahneely/kidmergencies pull request #60
Opened 2017-12-05 04:55 UTC by espinozamaria

Login and Registration back-end connected to front-end! :D

2017-12-06 18:09 UTC, bexinthesky requested changes
My only comment would be to change your var's to const's - unless they need to be var instead of const

2017-12-06 18:12 UTC, ayojackay approved these changes

2017-12-06 18:12 UTC, ayojackay commented
No merge issues at this time.

2017-12-06 21:46 UTC, espinozamaria commented
Changed vars to consts! Sorry about that!

2017-12-06 21:46 UTC, bexinthesky approved these changes

2017-12-06 22:02 UTC, ayojackay approved these changes

2017-12-07 02:09 UTC, sarahneely approved these changes

2017-12-07 02:09 UTC, merged