Issue5
sarahneely/kidmergencies pull request #62
Opened 2017-12-07 04:14 UTC by sarahneely

Styles created for the main settings page

2017-12-07 04:57 UTC, bexinthesky requested changes
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,700,900');
just add the sizes so that they import properly

2017-12-09 00:46 UTC, espinozamaria commented
After changes Rebecca requested are fixed, I think it should be perfect to merge! 😄

2017-12-09 00:47 UTC, espinozamaria approved these changes

2017-12-09 02:21 UTC, bexinthesky approved these changes

2017-12-09 06:22 UTC, ayojackay commented
I have no issues with this pull request. I'm about to merge.

2017-12-09 19:12 UTC, merged